ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-42}"
ARG BUILDER_IMAGE="${BUILDER_IMAGE:-quay.io/fedora/fedora}"
ARG BUILDER_BASE="${BUILDER_IMAGE}:${FEDORA_MAJOR_VERSION}"
FROM ${BUILDER_BASE} AS builder

ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-42}"
ARG KERNEL_FLAVOR="${KERNEL_FLAVOR:-main}"
ARG RPMFUSION_MIRROR=""
ARG DUAL_SIGN="true"

ARG KMODS_TO_BUILD=""

COPY build_files/common build_files/shared /tmp/
COPY kmods.yaml /tmp/kmods.yaml
COPY certs /tmp/certs

# KMOD_COPR_REPOS_ADD_INSTRUCTIONS
# This section will be populated by get_kmods_to_build.sh with ADD instructions for COPR repos.

RUN --mount=type=bind,src=kernel_cache,dst=/tmp/kernel_cache,ro \
    --mount=type=cache,dst=/var/cache/dnf \
    ls -sh /tmp/kernel_cache; \
    if grep -qv "surface" <<< "${KERNEL_FLAVOR}"; then \
        export KERNEL_NAME="kernel" \
    ; else \
        export KERNEL_NAME="kernel-surface" \
    ; fi && \
    /tmp/build-prep.sh && \
    if [[ "${KERNEL_FLAVOR}" =~ "coreos" ]]; then \
      /tmp/build-ublue-os-ucore-addons.sh && \
      cp /tmp/ublue-os-ucore-addons/rpmbuild/RPMS/noarch/ublue-os-ucore-addons*.rpm \
        /var/cache/rpms/ucore/ \
    ; fi && \
    /tmp/build-ublue-os-akmods-addons.sh && \
    cp /tmp/ublue-os-akmods-addons/rpmbuild/RPMS/noarch/ublue-os-akmods-addons*.rpm \
      /var/cache/rpms/ublue-os/ && \
    # KMOD_INSTALL_AND_BUILD_COMMANDS
    # This section will be populated by get_kmods_to_build.sh with dnf install and akmods --force commands.
    /tmp/dual-sign.sh && \
    /tmp/build-post.sh

FROM scratch

COPY --from=builder /var/cache/kernel-rpms /kernel-rpms
COPY --from=builder /var/cache/rpms /rpms
